#!/bin/bash
echo "=== PRE-LAUNCH CHECKLIST ==="
echo "[ ] Token name finalized"
echo "[ ] Telegram created with 20+ members"
echo "[ ] Twitter account created"
echo "[ ] 5+ memes ready"
echo "[ ] Community engaged"
echo "[ ] Launch time picked (6-8 AM UTC preferred)"
echo "[ ] Free SOL ready for gas (~0.01 SOL)"
echo ""
echo "=== POST-LAUNCH ==="
echo "[ ] Renounce ownership immediately"
echo "[ ] Lock LP on Raydium"
echo "[ ] Share in 20+ Telegram groups"
echo "[ ] Pin message in your group"
